### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by gvenka008c** [rji/jenkins-standalone#5]
Can this be run without redis?
./jenkins-standalone.sh -z $(cat /etc/mesos/zk) -r redis.example.com -u jenkins -d example/docker-image

**Comment by rji** [comment]
Yes, you could modify the script to not require Redis / Logstash, but keep in mind that you'll want your Jenkins master to store build history and state somewhere. Otherwise, if the Mesos task is ever re-launched, you'll lose all your build information in the Mesos sandbox. This project in particular was meant for Jenkins masters to be ephemeral, and for all state to be shipped to ELK.

If you have a distributed filesystem or NFS available at the same mount point on each machine in the Mesos cluster, you might want to take a look at http://mesosphere.github.io/jenkins-mesos, which is another project I contribute to. Currently it allows you to specify a path on the host (it was designed with NFS in mind) so that the Jenkins master can run anywhere in the Mesos cluster without risking the loss of your job configurations and build history. Eventually we'd like to move away from this and use the persistence primitives that are being built into Mesos.
